"""
Awareness & Literacy module — Yasemin Günindi
Adds contextual annotations to predictions so stakeholders understand AI limitations.
"""

import pandas as pd


# Literacy annotations shown alongside every prediction output
_SYSTEM_DISCLAIMER = (
    "This risk score is generated by a machine learning model trained on historical "
    "Open University data. It is a decision-support tool — not a final verdict. "
    "Predictions may reflect historical inequalities in the training data. "
    "Always involve a human advisor before taking action."
)

_DATA_COLLECTION_NOTE = (
    "Data used: VLE click activity, assignment scores, registration records. "
    "No real-time monitoring. Data collected under the institution's privacy policy."
)

_LIMITATION_NOTE = (
    "Limitations: The model does not account for personal circumstances, "
    "health issues, or recent life events. Accuracy varies across student groups."
)


def print_awareness_header():
    """Prints the AI literacy header before any prediction output is shown."""
    print("=" * 60)
    print("AI EARLY-WARNING SYSTEM — AWARENESS & LITERACY NOTICE")
    print("=" * 60)
    print(_SYSTEM_DISCLAIMER)
    print()
    print(_DATA_COLLECTION_NOTE)
    print()
    print(_LIMITATION_NOTE)
    print("=" * 60)


def annotate_prediction(student_id, risk_label: str, confidence: float) -> str:
    """
    Returns a full annotated prediction string for a single student.
    risk_label: 'At-Risk' or 'Pass'
    confidence: model probability for the predicted class
    """
    lines = [
        f"Student {student_id}: predicted → {risk_label} (confidence: {confidence:.1%})",
        "",
        "What this means:",
        "  - 'At-Risk' suggests the student may benefit from early support.",
        "  - This is NOT a guarantee of failing. Many 'at-risk' students pass.",
        "  - An advisor should review this flag before any action is taken.",
        "",
        "Your rights:",
        "  - You may request a review of this prediction.",
        "  - You may ask which factors contributed to this score.",
        "  - You are not obliged to disclose personal circumstances.",
    ]
    return "\n".join(lines)


def generate_educator_briefing(mf_summary: pd.DataFrame) -> str:
    """
    Generates a short briefing for educators summarizing model performance
    and known bias risks across student groups.
    """
    lines = [
        "=== EDUCATOR BRIEFING ===",
        "The model's fairness audit shows the following per-group accuracy:",
        str(mf_summary),
        "",
        "Interpretation guidance:",
        "  - Groups with lower accuracy may be systematically mis-classified.",
        "  - Do not use predictions as the sole basis for intervention decisions.",
        "  - Consider supplementary qualitative assessment for flagged students.",
    ]
    return "\n".join(lines)
